@startuml

title __PRESENTATION's Class Diagram__\n
!define DARKORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

  namespace wasteless.server {
    namespace presentation {
      class wasteless.server.presentation.GroceryListController {
          + GroceryListController()
          + calculateWaste()
          + createGroceryList()
          + deleteGroceryList()
          + generateJsonReport()
          + generateTextReport()
          + getAllGroceryLists()
          + getGroceryListById()
          + updateGroceryList()
      }
      class wasteless.server.presentation.ItemController {
                + ItemController()
                + createItem()
                + deleteItem()
                + getAllItems()
                + getItemById()
                + updateItem()
      }
      class wasteless.server.presentation.UserController {
                + UserController()
                + createUser()
                + deleteUser()
                + getActiveUser()
                + getAllUsers()
                + getUSerById()
                + loginUser()
                + updateUser()
            }
    }

    namespace business {
          class wasteless.server.business.ExportService {
              + ExportService()
              + exportJsonWasteReport()
              + exportTextWasteReport()
              - getReportGenerator()
          }

           class wasteless.server.business.GroceryListService {
                    + GroceryListService()
                    + createGroceryList()
                    + deleteGroceryList()
                    + getAllGroceryLists()
                    + getGroceryListById()
                    + updateGroceryList()
                }

               class wasteless.server.business.ItemService {
                         + ItemService()
                         + createItem()
                         + deleteItem()
                         + getAllItems()
                         + getItemById()
                         + updateItem()
                     }

          class wasteless.server.business.UserService {
                    + UserService()
                    + createUser()
                    + deleteUser()
                    + getActiveUser()
                    + getAllUsers()
                    + getUserById()
                    + loginUser()
                    + updateUser()
                }

           class wasteless.server.business.WasteManagerService {
                     + getTotalCalories()
                 }



        }

         namespace persistance {
              interface wasteless.server.persistance.GroceryListRepository {
              }

               interface wasteless.server.persistance.ItemRepository {
                    }
              interface wasteless.server.persistance.UserRepository {
                       {abstract} + findFirstByActiveTrue()
                   }
            }
  }





  wasteless.server.presentation.GroceryListController o-- wasteless.server.business.ExportService : exportService
  wasteless.server.presentation.GroceryListController o-- wasteless.server.presentation.mapper.GroceryListMapper : groceryListMapper
  wasteless.server.presentation.GroceryListController o-- wasteless.server.business.GroceryListService : groceryListService
  wasteless.server.presentation.GroceryListController o-- wasteless.server.business.WasteManagerService : wasteManagerService
  wasteless.server.presentation.ItemController o-- wasteless.server.presentation.mapper.ItemMapper : itemMapper
  wasteless.server.presentation.ItemController o-- wasteless.server.business.ItemService : itemService
  wasteless.server.presentation.UserController o-- wasteless.server.presentation.mapper.UserMapper : userMapper
  wasteless.server.presentation.UserController o-- wasteless.server.business.UserService : userService



 wasteless.server.business.ExportService o-- wasteless.server.export.factory.FactoryProvider : factoryProvider
  wasteless.server.business.GroceryListService o-- wasteless.server.presentation.mapper.GroceryListMapper : groceryListMapper
  wasteless.server.business.GroceryListService o-- wasteless.server.persistance.GroceryListRepository : groceryListRepository
  wasteless.server.business.GroceryListService o-- wasteless.server.persistance.UserRepository : userRepository
  wasteless.server.business.ItemService o-- wasteless.server.persistance.GroceryListRepository : groceryListRepository
  wasteless.server.business.ItemService o-- wasteless.server.persistance.ItemRepository : itemRepository
  wasteless.server.business.UserService o-- wasteless.server.persistance.UserRepository : userRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml