@startuml

title __DTO's Class Diagram__\n

  namespace wasteless.server {
    namespace presentation {
      namespace dto {
        class wasteless.server.presentation.dto.GroceryListDTO {
            - groceryListId : long
            - groceryListName : String
            - userId : long
            + getGroceryListId()
            + getGroceryListName()
            + getUserId()
            + setGroceryListId()
            + setGroceryListName()
            + setUserId()
        }
      }
    }
  }
  

  namespace wasteless.server {
    namespace presentation {
      namespace dto {
        class wasteless.server.presentation.dto.ItemDTO {
            - calorieValue : float
            - consumptionDate : LocalDate
            - expirationDate : LocalDate
            - itemId : long
            - itemName : String
            - purchaseDate : LocalDate
            - quantity : float
            + getCalorieValue()
            + getConsumptionDate()
            + getExpirationDate()
            + getItemId()
            + getItemName()
            + getPurchaseDate()
            + getQuantity()
            + setCalorieValue()
            + setConsumptionDate()
            + setExpirationDate()
            + setItemId()
            + setItemName()
            + setPurchaseDate()
            + setQuantity()
        }
      }
    }
  }
  

  namespace wasteless.server {
    namespace presentation {
      namespace dto {
        class wasteless.server.presentation.dto.UserDTO {
            - active : boolean
            - emailAddress : String
            - firstName : String
            - id : Long
            - lastName : String
            - password : String
            + getEmailAddress()
            + getFirstName()
            + getId()
            + getLastName()
            + getPassword()
            + isActive()
            + setActive()
            + setEmailAddress()
            + setFirstName()
            + setId()
            + setLastName()
            + setPassword()
        }
      }
    }
  }
  

  namespace wasteless.server {
    namespace presentation {
      namespace dto {
        class wasteless.server.presentation.dto.WasteCalculatorDTO {
            - burndownRateGoal : Integer
            - calculationDate : LocalDate
            - groceryListName : String
            - wasteResult : Integer
            + getBurndownRateGoal()
            + getCalculationDate()
            + getGroceryListName()
            + getWasteResult()
            + setBurndownRateGoal()
            + setCalculationDate()
            + setGroceryListName()
            + setWasteResult()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
